language: c
sudo: false
addons:
  apt:
    packages:
    - texinfo
cache:
  directories:
    mpir-2.7.0
    mpfr-3.1.3
    flint-2.5.2
script:
  - ./.build_dependencies && ./configure --with-gmp=mpir-2.7.0 --with-mpfr=mpfr-3.1.3 --with-flint=flint-2.5.2 --disable-static && make && make check

